const cart = [
    {
        id: "1",
        img: "assets/images/products/img-4.png",
        title: "Borosil Paper Cup",
        color: "red",
        size: "M",
        price: "24.00",
        qty: 2,
        bgcolor: "warning",
        stock: "In Stock",
    },
    {
        id: "2",
        img: "assets/images/products/img-1.png",
        title: "Rockerz Ear Bluetooth Hea...",
        color: "Brown",
        price: "160.00",
        qty: 1,
        bgcolor: "info",
        stock: "In Stock",
    },
    {
        id: "3",
        img: "assets/images/products/img-6.png",
        title: "Monte Carlo Sweaters",
        color: "Orange",
        size: "XL",
        price: "244.99",
        qty: 3,
        bgcolor: "danger",
        stock: "In Stock",
    },
    {
        id: "4",
        img: "assets/images/products/img-8.png",
        title: "Men's Running Shoes Act...",
        color: "White",
        price: "120.30",
        qty: 2,
        bgcolor: "primary",
        stock: "In Stock",
    },
];

export { cart };
