const productData = [
  {
    id: "1",
    name: "Man Relaxed Fit T-shirt",
    image: "assets/images/products/img-6.png",
    price: "199.00",
    mrp: "425.00",
    rate: "4.9",
    tag: true,
    type: "best seller",
    color: "warning",
  },
  {
    id: "2",
    name: "Innovative education book ",
    image: "assets/images/products/img-7.png",
    price: "129.00",
    mrp: "",
    rate: "3.2",
    type: "best seller",
    color: "info",
  },
  {
    id: "1",
    name: "Hp Trendsetter Backpack",
    image: "assets/images/products/img-1.png",
    price: "299.00",
    mrp: "399.00",
    rate: "4.3",
    type: "hot collection",
    color: "danger",
  },
  {
    id: "1",
    name: "Hoodie Newyorker Winter Clothes",
    image: "assets/images/products/img-2.png",
    price: "159.00",
    mrp: "",
    rate: "3.1",
    type: "trendy",
    color: "warning",
  },
  {
    id: "1",
    name: "Leather band Smartwatches",
    image: "assets/images/products/img-3.png",
    price: "159.00",
    mrp: "",
    rate: "3.7",
    tag: true,
    type: "trendy",
    color: "danger",
  },
  {
    id: "1",
    name: "Slippers Open Toe",
    image: "assets/images/products/img-4.png",
    price: "169.00",
    mrp: "225.00",
    rate: "2.6",
    type: "best seller",
    color: "success",
  },
  {
    id: "1",
    name: "T-shirt Geometric Print pattern",
    image: "assets/images/products/img-8.png",
    price: "339.00",
    mrp: "",
    rate: "4.9",
    type: "hot collection",
    color: "info",
  },
  {
    id: "1",
    name: "Leather sports shoes on wood",
    image: "assets/images/products/img-5.png",
    price: "435.00",
    mrp: "636.00",
    rate: "4.9",
    tag: true,
    type: "new",
    color: "danger",
  },
];

const latest_arrival = [
  {
    img: "assets/images/products/img-9.png",
    title: "Petronas Baseball Cap",
    price: "125.00",
    mrp: "200.00",
    rating: 3.2,
    bgcolor: "dark",
  },
  {
    img: "assets/images/products/img-10.png",
    title: "Mens Black T Shirt",
    price: "150.00",
    mrp: "300.00",
    rating: 4.3,
    bgcolor: "warning",
  },
  {
    img: "assets/images/products/img-11.png",
    title: "Blue Checked Slim Fit Shirt",
    price: "135.00",
    mrp: "523.00",
    rating: 2.3,
    bgcolor: "primary",
  },
  {
    img: "assets/images/products/img-12.png",
    title: "Onyx SmartGRID Chair Red",
    price: "99.00",
    mrp: "129.00",
    rating: 3.5,
    bgcolor: "danger",
  },
  {
    img: "assets/images/products/img-14.png",
    title: "Nursing Chair Steam Grey",
    price: "632.00",
    mrp: "721.00",
    rating: 2.3,
    bgcolor: "secondary",
  },
];

export { productData, latest_arrival };
