const orderhistory = [
    {
        id: "1",
        order_id: "TBT15454841",
        img: "assets/images/products/img-19.png",
        title: "World's Most Expensive T Shirt",
        type: "Women's Clothes",
        date: "01 Jul, 2022",
        amount: "287.53",
        status: "Delivered",
        bgcolor: "light",
    },
    {
        id: "2",
        order_id: "TBT15425012",
        img: "assets/images/products/img-12.png",
        title: "Onyx SmartGRID Chair Red",
        type: "Furniture & Decore",
        date: "01 Feb, 2023",
        amount: "39.99",
        status: "Shipping",
        bgcolor: "danger",
    },
    {
        id: "3",
        order_id: "TBT1524563",
        img: "assets/images/products/img-4.png",
        title: "Slippers Open Toe",
        type: "Footwear",
        date: "09 Dec, 2022",
        amount: "874.00",
        status: "Out Of Delivery",
        bgcolor: "success",
    },
    {
        id: "4",
        order_id: "TBT1524530",
        img: "assets/images/products/img-1.png",
        title: "Hp Trendsetter Backpack",
        type: "Handbags & Clutches",
        date: "02 Jan, 2023",
        amount: "32.00",
        status: "Delivered",
        bgcolor: "secondary",
    },
    {
        id: "5",
        order_id: "TBT13642870",
        img: "assets/images/products/img-7.png",
        title: "Innovative education book",
        type: "Books",
        date: "08 Jan, 2023",
        amount: "18.32",
        status: "Pending",
        bgcolor: "info",
    },
];

export { orderhistory };
